
import openpyxl as xl
from openpyxl.styles import Font,Alignment,PatternFill,Border,Side
from openpyxl.utils import get_column_letter as gcl
wb=xl.Workbook()
ws=wb.active
ws.title='TestCases'
H=['Test Case#','Test Title / Scenario','Test Summary','Test Steps','Test Data','Expected Result','Post-condition']
W=[14,32,38,55,42,42,40]
hfill=PatternFill('solid',fgColor='1F4E79')
hfont=Font(bold=True,color='FFFFFF',size=10)
t=Side(style='thin')
bd=Border(left=t,right=t,top=t,bottom=t)
al=Alignment(wrap_text=True,vertical='top')
for i,v in enumerate(H,1):
    c=ws.cell(1,i,v);c.font=hfont;c.fill=hfill;c.alignment=al;c.border=bd
    ws.column_dimensions[gcl(i)].width=W[i-1]
ws.row_dimensions[1].height=30
fills=[PatternFill('solid',fgColor=x) for x in ['EBF3FB','D6E4F0','EBF3FB','D6E4F0','EBF3FB','D6E4F0','EBF3FB','D6E4F0','EBF3FB','D6E4F0']]
def row(r,tc,title,smry,steps,data,exp,post,ridx):
    vals=[tc,title,smry,steps,data,exp,post]
    f=fills[ridx%10]
    for i,v in enumerate(vals,1):
        c=ws.cell(r,i,v);c.alignment=al;c.border=bd;c.fill=f
    ws.row_dimensions[r].height=80


tcs=[
['TC_AUTH_01','Đăng ký thành công','Kiểm tra đăng ký tài khoản mới hợp lệ','1. Vào trang /User/DangKy\n2. Nhập họ tên: Nguyễn Văn A\n3. Nhập email: test_new@gmail.com\n4. Nhập mật khẩu: Abc123\n5. Nhập SĐT: 0912345678\n6. Click Đăng Ký','Họ tên: Nguyễn Văn A\nEmail: test_new@gmail.com\nMật khẩu: Abc123\nSĐT: 0912345678','Hệ thống chuyển hướng về trang Đăng Nhập, tài khoản mới được tạo','DB: Bảng KHACHHANG có bản ghi mới với MAKH tự động sinh, EMAIL=test_new@gmail.com'],
['TC_AUTH_02','Đăng ký - Email trùng','Kiểm tra hệ thống xử lý khi email đã tồn tại','1. Vào trang /User/DangKy\n2. Nhập email: khoa@gmail.com (đã tồn tại)\n3. Nhập các trường còn lại hợp lệ\n4. Click Đăng Ký','Email: khoa@gmail.com (đã dùng)\nMật khẩu: Abc123','Hệ thống báo lỗi email đã được sử dụng hoặc insert lỗi UNIQUE violation','DB: Không có bản ghi mới trong KHACHHANG'],
['TC_AUTH_03','Đăng ký - Bỏ trống họ tên','Kiểm tra validation trường bắt buộc','1. Vào trang Đăng Ký\n2. Bỏ trống trường Họ tên\n3. Điền các trường khác hợp lệ\n4. Click Đăng Ký','Họ tên: (trống)\nEmail: abc@gmail.com\nMật khẩu: Abc123','Hệ thống báo lỗi: Vui lòng nhập họ tên','DB: Không có bản ghi mới'],
['TC_AUTH_04','Đăng ký - Mật khẩu < 6 ký tự','BVA: Kiểm tra mật khẩu 5 ký tự (dưới giới hạn)','1. Vào trang Đăng Ký\n2. Nhập mật khẩu: Ab123 (5 ký tự)\n3. Click Đăng Ký','Mật khẩu: Ab123 (5 ký tự)','Hệ thống báo lỗi: Mật khẩu phải có ít nhất 6 ký tự','DB: Không có bản ghi mới'],
['TC_AUTH_05','Đăng ký - Mật khẩu = 6 ký tự','BVA: Kiểm tra mật khẩu 6 ký tự (chính xác giới hạn)','1. Vào trang Đăng Ký\n2. Nhập mật khẩu: Ab1234 (6 ký tự)\n3. Click Đăng Ký','Mật khẩu: Ab1234 (6 ký tự chính xác)','Đăng ký thành công, tài khoản được tạo','DB: KHACHHANG có bản ghi mới với MATKHAU=Ab1234'],
['TC_AUTH_06','Đăng ký - Email sai định dạng','EP Negative: Email không hợp lệ','1. Vào trang Đăng Ký\n2. Nhập email: abc-khong-hop-le\n3. Click Đăng Ký','Email: abc-khong-hop-le','Hệ thống báo lỗi định dạng email không hợp lệ','DB: Không có bản ghi mới'],
['TC_AUTH_07','Đăng ký - SĐT sai định dạng','BVA: SĐT không đủ 10 số','1. Vào trang Đăng Ký\n2. Nhập SĐT: 091234 (6 số)\n3. Click Đăng Ký','SĐT: 091234 (6 số, dưới giới hạn)','Hệ thống báo lỗi: SĐT phải đủ 10 số','DB: Không có bản ghi mới'],
['TC_AUTH_08','Đăng nhập User thành công','Kiểm tra đăng nhập khách hàng hợp lệ','1. Vào trang /User/DangNhap\n2. Nhập email: khoa@gmail.com\n3. Nhập mật khẩu: 123456\n4. Click Đăng Nhập','Email: khoa@gmail.com\nMật khẩu: 123456','Hệ thống chuyển hướng về TrangChu, Session[UserName] = KH01','Session[UserName] = đối tượng KHACHHANG của KH01'],
['TC_AUTH_09','Đăng nhập - Sai mật khẩu','Negative: Mật khẩu không chính xác','1. Vào trang Đăng Nhập\n2. Nhập email: khoa@gmail.com\n3. Nhập mật khẩu: SaiMk999\n4. Click Đăng Nhập','Email: khoa@gmail.com\nMật khẩu: SaiMk999','Hiển thị thông báo: Mật khẩu không chính xác! Giữ nguyên Session[Email]','Session[UserName]=null, Session[Email]=khoa@gmail.com'],
['TC_AUTH_10','Đăng nhập - Email không tồn tại','Negative: Email chưa đăng ký','1. Vào trang Đăng Nhập\n2. Nhập email: khongton@gmail.com\n3. Nhập mật khẩu: bat_ky\n4. Click Đăng Nhập','Email: khongton@gmail.com','Hiển thị thông báo: Email không chính xác!','Session[UserName]=null, Session[ErrorEmail] được gán'],
['TC_AUTH_11','Đăng nhập Admin - CV05 thành công','Kiểm tra đăng nhập Admin với chức vụ CV05 (Quản lý cấp cao)','1. Vào trang Đăng Nhập\n2. Nhập Mã NV: NV05\n3. Nhập Mật khẩu: admin123\n4. Click Đăng Nhập Admin','Mã NV: NV05\nMật khẩu: admin123\nChức vụ: CV05','Chuyển hướng về /Admin/TrangChu, Session[AdminUser] được gán','Session[AdminUser] = NV05, có quyền Admin đầy đủ (CV05)'],
['TC_AUTH_12','Đăng nhập Admin - CV09 thành công','Kiểm tra đăng nhập Giám đốc sân bay (CV09)','1. Vào trang Đăng Nhập\n2. Nhập Mã NV: NV09\n3. Nhập Mật khẩu: admin123\n4. Click Đăng Nhập Admin','Mã NV: NV09\nMật khẩu: admin123\nChức vụ: CV09','Chuyển hướng về /Admin/TrangChu thành công','Session[AdminUser] = NV09, có quyền Admin (CV09)'],
['TC_AUTH_13','Đăng nhập Admin - CV01 bị từ chối','Phân quyền: Nhân viên bán vé không có quyền Admin','1. Vào trang Đăng Nhập\n2. Nhập Mã NV: NV01 (CV01)\n3. Nhập Mật khẩu: 123456\n4. Click Đăng Nhập Admin','Mã NV: NV01\nMật khẩu: 123456\nChức vụ: CV01','Hệ thống báo lỗi hoặc chuyển về trang không có quyền, không vào được /Admin','Session[AdminUser]=null, redirect về trang lỗi phân quyền'],
['TC_AUTH_14','Đổi mật khẩu thành công','Kiểm tra đổi mật khẩu hợp lệ','1. Đăng nhập thành công với KH01\n2. Vào Trang Cá Nhân / HoSo\n3. Nhập mật khẩu hiện tại: 123456\n4. Nhập mật khẩu mới: NewPass7\n5. Nhập xác nhận: NewPass7\n6. Click Lưu','Mật khẩu hiện tại: 123456\nMật khẩu mới: NewPass7\nXác nhận: NewPass7','Hiển thị thông báo: Đổi mật khẩu thành công!','DB: KHACHHANG.MATKHAU của KH01 = NewPass7'],
['TC_AUTH_15','Đổi mật khẩu - Mật khẩu hiện tại sai','Negative: Kiểm tra xác thực mật khẩu cũ','1. Đăng nhập KH01\n2. Vào HoSo\n3. Nhập mật khẩu hiện tại: SaiRoi\n4. Nhập mật khẩu mới: NewPass7\n5. Click Lưu','Mật khẩu hiện tại: SaiRoi (sai)\nMật khẩu mới: NewPass7','Hiển thị lỗi: Mật khẩu hiện tại không chính xác','DB: MATKHAU của KH01 không thay đổi'],
['TC_AUTH_16','Đổi mật khẩu - Xác nhận không khớp','Negative: Mật khẩu mới và xác nhận khác nhau','1. Đăng nhập KH01\n2. Vào HoSo\n3. Nhập mật khẩu hiện tại: 123456\n4. Nhập mật khẩu mới: NewPass7\n5. Nhập xác nhận: DiffPass8\n6. Click Lưu','Mật khẩu mới: NewPass7\nXác nhận: DiffPass8 (khác)','Hiển thị lỗi: Mật khẩu xác nhận không khớp','DB: MATKHAU không thay đổi'],
['TC_AUTH_17','Đổi mật khẩu - Mật khẩu mới < 6 ký tự','BVA: Mật khẩu mới 5 ký tự','1. Đăng nhập KH01\n2. Vào HoSo\n3. Nhập mật khẩu hiện tại: 123456\n4. Nhập mật khẩu mới: Ab123 (5 ký tự)\n5. Click Lưu','Mật khẩu mới: Ab123 (5 ký tự)','Hiển thị lỗi: Mật khẩu mới phải có ít nhất 6 ký tự','DB: MATKHAU không thay đổi']
]
r=2
for i,tc in enumerate(tcs):
    row(r,*tc,i)
    r+=1


tcs2=[
['TC_DATVE_01','Tìm kiếm chuyến bay một chiều','Kiểm tra tìm kiếm chuyến bay 1 chiều hợp lệ','1. Đăng nhập thành công\n2. Vào trang TrangChu\n3. Chọn loại chuyến: Một chiều\n4. Nhập Điểm đi: Hồ Chí Minh\n5. Nhập Điểm đến: Hà Nội\n6. Chọn Ngày đi: 29/12/2025\n7. Chọn 1 hành khách\n8. Click Tìm chuyến','Loại: Một chiều\nĐiểm đi: Hồ Chí Minh\nĐiểm đến: Hà Nội\nNgày đi: 29/12/2025\nHành khách: 1','Hiển thị danh sách chuyến bay CB01 (HCM->HN) vào 29/12, có giá 1.950.000đ','Session[ListChuyenBay] chứa các chuyến bay lọc theo điều kiện'],
['TC_DATVE_02','Tìm kiếm chuyến bay khứ hồi','Kiểm tra luồng tìm kiếm khứ hồi 2 chiều','1. Chọn loại: Khứ hồi\n2. Điểm đi: Hà Nội, Điểm đến: Đà Nẵng\n3. Ngày đi: 30/12/2025, Ngày về: 05/01/2026\n4. Hành khách: 2\n5. Click Tìm chuyến','Loại: Khứ hồi\nĐi: Hà Nội -> Đà Nẵng (30/12)\nVề: Đà Nẵng -> Hà Nội (05/01/2026)\nHành khách: 2','Hiển thị chọn chuyến chiều đi trước, Session[Chieu]=Chọn chuyến cho chiều đi, sau khi chọn thì chuyển sang chiều về','Session[round2]=true, Session[DiemDi], DiemDen, NgayDi, NgayVe được lưu'],
['TC_DATVE_03','Tìm kiếm - Hành khách = 0','BVA: Hành khách dưới giới hạn tối thiểu','1. Chọn Một chiều\n2. Nhập Hành khách: 0\n3. Click Tìm chuyến','Hành khách: 0','Hệ thống báo lỗi hoặc bỏ qua giá trị 0, không tìm kiếm','Session[passenger] không được ghi giá trị <= 0'],
['TC_DATVE_04','Tìm kiếm - Hành khách = 1','BVA: Hành khách tại giới hạn tối thiểu','1. Chọn Một chiều\n2. Nhập Hành khách: 1\n3. Click Tìm chuyến với đủ điều kiện','Hành khách: 1','Tìm kiếm thành công, hiển thị chuyến bay phù hợp','Session[passenger]=1'],
['TC_DATVE_05','Tìm kiếm - Hành khách = 9','BVA: Hành khách tại giới hạn tối đa','1. Chọn Một chiều\n2. Nhập Hành khách: 9\n3. Click Tìm chuyến','Hành khách: 9','Tìm kiếm thành công, hiển thị chuyến bay','Session[passenger]=9'],
['TC_DATVE_06','Lọc chuyến - Giá dưới 2 triệu','Kiểm tra lọc theo khoảng giá < 2.000.000','1. Tìm kiếm chuyến xong\n2. Tích ô lọc giá: Dưới 2 triệu\n3. Click Lọc','Giá: Dưới 2.000.000\nSession[ListOld] chứa các chuyến','Chỉ hiển thị các chuyến bay có GIA_COSO < 2.000.000 (VD: CB02=1.5tr, CB06=1.3tr)','Session[ListChuyenBay] chỉ chứa chuyến có giá < 2tr'],
['TC_DATVE_07','Lọc chuyến - Giá từ 2-5 triệu','Kiểm tra lọc theo khoảng giá 2-5 triệu','1. Tìm kiếm chuyến xong\n2. Tích ô lọc giá: 2 đến 5 triệu\n3. Click Lọc','Giá: 2.000.000 - 5.000.000','Chỉ hiển thị chuyến có giá >= 2tr và <= 5tr','Session[ListChuyenBay] lọc theo khoảng giá'],
['TC_DATVE_08','Lọc chuyến - Hạng Phổ thông','Kiểm tra lọc theo hạng ghế Phổ thông','1. Tìm kiếm chuyến\n2. Tích lọc Hạng ghế: Phổ thông\n3. Click Lọc','Hạng ghế: Phổ thông','Chỉ hiển thị vé hạng Phổ thông','Session[Filter_HangGhe]=[Phổ thông]'],
['TC_DATVE_09','Lọc chuyến - Giờ sáng','Kiểm tra lọc theo giờ cất cánh buổi sáng (6h-12h)','1. Tìm kiếm chuyến\n2. Tích lọc Giờ cất cánh: Sáng\n3. Click Lọc','Giờ cất cánh: 6:00 - 11:59','Chỉ hiển thị chuyến có GioCatCanh trong khoảng 6h-12h','Session[Filter_Gio]=[sang]'],
['TC_DATVE_10','Sắp xếp giá tăng dần','Kiểm tra sort chuyến bay theo giá từ thấp đến cao','1. Tìm kiếm xong\n2. Click Sort: Giá thấp nhất','Sort: min','Các chuyến bay hiển thị theo thứ tự giá tăng dần','Session[ListChuyenBay] được sắp xếp theo Giá ASC'],
['TC_DATVE_11','Chọn ghế - Ghế trống','Kiểm tra chọn ghế trống (chưa có ai đặt)','1. Đăng nhập, tìm chuyến CB01\n2. Chọn 1 hành khách\n3. Vào trang ChonCho\n4. Click vào ghế 15A (trống)','Ghế: 15A (chưa trong VEMAYBAy, chưa trong GIOHANG_HANHKHACH)','Ghế 15A được chọn, hiển thị form nhập thông tin hành khách','Ghế chưa được lưu vào DB cho đến khi LuuVaoGioHang'],
['TC_DATVE_12','Chọn ghế - Ghế đã bán','Kiểm tra các ghế đã có trong VEMAYBAYs bị đánh dấu không chọn','1. Tìm chuyến CB01\n2. Vào trang ChonCho\n3. Quan sát ghế 12A (đã có trong VEMAYBAY.CB01)','Ghế: 12A (đã bán - GH01/CB01)','Ghế 12A hiển thị trạng thái đã bán (màu đỏ/khóa), không thể chọn','GheDaDat chuẩn bao gồm TENGHE=12A'],
['TC_DATVE_13','Lưu ghế bị chiếm đồng thời','Kiểm tra race condition khi 2 người cùng chọn 1 ghế','1. User A và User B cùng chọn ghế 10B của CB04\n2. User A lưu trước\n3. User B lưu sau','2 users cùng chọn SOGHE=10B, MACB=CB04','User B nhận lỗi: Ghế 10B vừa được người khác chọn. Redirect về ChonCho','DB: Chỉ 1 bản ghi trong GIOHANG_HANHKHACH với SOGHE=10B/CB04'],
['TC_DATVE_14','Thêm hành lý xách tay','Kiểm tra chọn hành lý xách tay khi nhập thông tin hành khách','1. Đăng nhập, vào ChonCho CB01\n2. Chọn ghế\n3. Nhập thông tin HK\n4. Chọn Hành lý xách tay\n5. Click Lưu','Hành lý xách tay: Có (phí phụ thêm)\nGhế: 15A, Hạng Phổ thông','Thông tin hành khách được lưu vào GIOHANG_HANHKHACH với HANGLY_XACHTAY > 0','DB: GIOHANG_HANHKHACH.HANGLY_XACHTAY != 0'],
['TC_DATVE_15','Thêm hành lý ký gửi','Kiểm tra chọn hành lý ký gửi','1. Vào ChonCho, chọn ghế\n2. Chọn Hành lý ký gửi (20kg)\n3. Click Lưu','Hành lý ký gửi: 20kg','Phí hành lý được cộng vào tổng tiền, lưu vào HANHLYKYGUI','DB: GIOHANG_HANHKHACH.HANHLYKYGUI != 0'],
['TC_DATVE_16','Nhập tuổi hành khách < 2','Trigger: HK dưới 2 tuổi bị từ chối','1. Vào ChonCho\n2. Nhập thông tin HK với NgaySinh: hôm nay - 1 năm (< 2 tuổi)\n3. Click Lưu','NGAYSINH: 2025-01-01 (mới sinh)','Hệ thống báo lỗi: Hành khách phải ít nhất 2 tuổi (Trigger trg_CheckTuoiHanhKhach)','DB: Không có bản ghi mới trong GIOHANG_HANHKHACH']
]
r2=r
for i,tc in enumerate(tcs2):
    row(r2,*tc,r-2+i)
    r2+=1
r=r2


tcs3=[
['TC_THANHTOAN_01','Thanh toán VNPay Demo - Thành công','Kiểm tra luồng thanh toán Online thành công','1. Đăng nhập KH01\n2. Chọn ghế, nhập HK, lưu vào giỏ hàng\n3. Vào trang ThanhToan\n4. Click Thanh toán VNPay\n5. Trên trang DemoVNPay, click Xác nhận Thành công','MAGH: GHxxx\nMaCB: CB01\npayment_method: vnpay','1. Giỏ hàng TRANGTHAI=Đã Thanh Toán\n2. Phiếu đặt vé mới tạo trong PHIEUDATVE\n3. Vé mới trong VEMAYBAY\n4. Chi tiết vé trong CHITIETVE\n5. TempData[PaymentSuccess]=true\n6. Redirect về VeCuaToi','DB: GIOHANG.TRANGTHAI=Đã Thanh Toán; VEMAYBAY có bản ghi mới; CHITIETVE có bản ghi mới; THONGKE_DOANHTHU tự động cập nhật qua Trigger'],
['TC_THANHTOAN_02','Thanh toán VNPay Demo - Hủy giao dịch','Kiểm tra luồng hủy thanh toán','1. Vào trang DemoVNPay\n2. Click Hủy giao dịch','Result: failure (hủy)','TempData[Error]=Bạn đã hủy giao dịch, redirect về trang ThanhToan','DB: Không có thay đổi nào trong PHIEUDATVE, VEMAYBAY, CHITIETVE'],
['TC_THANHTOAN_03','Đối soát tổng tiền với FN_TinhTongTien','Kiểm tra giá trên UI khớp với Function SQL','1. Tạo giỏ hàng GH với CB01, 2 HK hạng Phổ thông\n2. Xem trang ThanhToan\n3. Kiểm tra tổng tiền hiển thị\n4. Chạy SQL: SELECT dbo.FN_TinhTongTien(MAGH, MACB)','MAGH=GHxxx, MACB=CB01\nGiá Phổ thông CB01: 1.950.000 x 2 = 3.900.000','Tổng tiền trên UI = 3.900.000 = Kết quả FN_TinhTongTien','DB: GIOHANG_CHITIET.GIATIEN = 3.900.000 khớp với Function'],
['TC_THANHTOAN_04','Giỏ hàng hết hạn 15 phút','Kiểm tra giỏ hàng tự động xóa khi quá 15 phút','1. Tạo giỏ hàng, đặt ghế\n2. Chờ hơn 15 phút\n3. Vào trang VeCuaToi','THOIGIANGIU = GETDATE() + 15 phút (đã quá)','Các ghế được giải phóng, GIOHANG_CHITIET bị xóa, GIOHANG bị xóa hoặc cập nhật trạng thái','DB: GIOHANG_CHITIET không còn bản ghi hết hạn; GIOHANG.TRANGTHAI=Đã hết hạn'],
['TC_THANHTOAN_05','Thanh toán khi chưa đăng nhập','Kiểm tra bảo mật: chuyển hướng về đăng nhập','1. Không đăng nhập\n2. Truy cập trực tiếp /User/ThanhToanOnline','Không có Session[UserName]','Hệ thống redirect về trang Đăng Nhập','Session[UserName]=null, không tạo giao dịch'],
['TC_THANHTOAN_06','Tạo vé - Đối soát DB','Integration: Kiểm tra dữ liệu DB sau thanh toán','1. Thực hiện thanh toán thành công\n2. Kiểm tra DB:\n   - SELECT * FROM VEMAYBAY WHERE MAVE=...\n   - SELECT * FROM CHITIETVE WHERE MAVE=...\n   - SELECT * FROM PHIEUDATVE WHERE MAGH=...\n   - SELECT * FROM THONGKE_DOANHTHU','MAGH=GHxxx, MACB=CB01\nGiá: 1.950.000','1. VEMAYBAY: có bản ghi mới, GIAVE=1.950.000, MACB=CB01\n2. CHITIETVE: MAVE khớp, GIATIEN=1.950.000\n3. PHIEUDATVE: TRANGTHAI=Đã thanh toán\n4. THONGKE_DOANHTHU: SOLUONGVE tăng 1, TONGDOANHTHU tăng 1.950.000','Trigger trg_CapNhatDoanhThu chạy đúng, dữ liệu thống kê chính xác'],
['TC_CHECKIN_01','Check-in đúng thời điểm','Kiểm tra check-in hợp lệ: trước bay 24h-1h','1. Có vé đã thanh toán cho CB01 (cất cánh 12h sau GETDATE)\n2. Đăng nhập, vào trang Check-in\n3. Click Xác nhận Check-in trên vé hợp lệ','Thời điểm hiện tại: 2h trước cất cánh (nằm trong khoảng 24h-1h)\nMaVe: TKTxxxx','Hiển thị nút Check-in, xác nhận thành công, ghi nhận vào bảng CHECKIN','DB: CHECKIN có bản ghi mới, TRANGTHAI=Đã check-in, THOIGIAN_CHECKIN=NOW()'],
['TC_CHECKIN_02','Check-in trước 24h cất cánh','BVA: Check-in sớm hơn 24h, bị từ chối','1. Có vé thanh toán cho chuyến bay còn 25h nữa mới cất cánh\n2. Vào trang Check-in\n3. Click Xác nhận Check-in','Thời điểm: 25h trước cất cánh (ngoài khoảng)','Trả về: Chưa đến thời gian check-in (24h trước giờ bay)\nKhông cho check-in','DB: Không có bản ghi mới trong CHECKIN'],
['TC_CHECKIN_03','Check-in trong 1h trước bay','BVA: Check-in khi còn 30 phút, bị từ chối','1. Có vé thanh toán cho chuyến còn 30 phút cất cánh\n2. Vào trang Check-in\n3. Click Xác nhận Check-in','Thời điểm: 30 phút trước cất cánh (quá hạn)','Trả về: Đã hết thời gian check-in (đóng trước bay 1h)\nKhông cho check-in','DB: Không có bản ghi mới trong CHECKIN'],
['TC_CHECKIN_04','Check-in lần 2 (đã check-in)','Kiểm tra không thể check-in 2 lần','1. Đã check-in thành công lần 1\n2. Refresh trang, click Xác nhận Check-in lần 2','Vé đã có CHECKIN.TRANGTHAI=Đã check-in','Trả về: Vé này đã được check-in rồi, không cho check-in lại','DB: CHECKIN không tạo bản ghi trùng lặp'],
['TC_CHECKIN_05','Xem thẻ lên máy bay (Boarding Pass)','Kiểm tra hiển thị Boarding Pass sau check-in','1. Đã check-in thành công\n2. Click Xem thẻ lên máy bay','MaVe đã check-in','Hiển thị BoardingPass với: Tên HK, Số ghế, Hạng ghế, Sân bay đi/đến, Giờ cất cánh, Mã QR','Trang XemTheLenMayBay load đúng, dữ liệu khớp với VEMAYBAY và GIOHANG_HANHKHACH'],
['TC_CHECKIN_06','Check-in khi chưa đăng nhập','Bảo mật: redirect về đăng nhập','1. Không đăng nhập\n2. Truy cập /User/CheckIn','Session[UserName]=null','Hệ thống redirect về trang Đăng Nhập hoặc hiện ViewBag.ChuaDangNhap=true','Không có dữ liệu bị truy cập trái phép'],
['TC_CHECKIN_07','Check-in vé không thuộc về mình','Bảo mật: kiểm tra quyền sở hữu vé','1. Đăng nhập KH01\n2. Truy cập check-in bằng MaVe của KH02','MaVe thuộc KH02, đăng nhập KH01','Hệ thống redirect về trang Check-in, không cho xem/check-in vé của người khác','DB: Không có thay đổi nào trong CHECKIN'],
]
r3=r
for i,tc in enumerate(tcs3):
    row(r3,*tc,r-2+i)
    r3+=1
r=r3


tcs4=[
['TC_ADMIN_01','Thêm chuyến bay mới','Admin thêm chuyến bay mới hợp lệ','1. Đăng nhập Admin (NV05/CV05)\n2. Vào /Admin/QLChuyenBay\n3. Click Thêm chuyến bay\n4. Chọn Máy bay: MB01\n5. Trạng thái: Chờ bay\n6. Giờ cất cánh: 01/01/2026 08:00\n7. Giờ hạ cánh: 01/01/2026 10:00\n8. Click Lưu','MAMB: MB01\nTrangThai: Chờ bay\nGioCatCanh: 2026-01-01 08:00\nGioHaCanh: 2026-01-01 10:00','Chuyến bay mới được tạo, hiển thị trong danh sách QLChuyenBay','DB: CHUYENBAY có bản ghi mới với MACB tự sinh (CBxxx); LOTRINH có bản ghi mới'],
['TC_ADMIN_02','Sửa chuyến bay','Admin cập nhật thông tin chuyến bay','1. Đăng nhập Admin\n2. Vào QLChuyenBay\n3. Click Sửa trên chuyến CB01\n4. Cập nhật GioCatCanh mới\n5. Click Lưu','MACB: CB01\nGioCatCanh mới: 2025-12-29 09:00\nGioHaCanh mới: 2025-12-29 11:00','Hiển thị: Cập nhật chuyến bay thành công! Thông tin CB01 được cập nhật','DB: CHUYENBAY.CB01 và LOTRINH.CB01 được cập nhật đúng'],
['TC_ADMIN_03','Xóa chuyến bay chưa có vé','Kiểm tra xóa chuyến bay hợp lệ','1. Tạo chuyến bay mới CBtest (chưa có vé bán)\n2. Click Xóa CBtest','MACB: CBtest chưa có vé, chưa trong giỏ hàng','Hiển thị: Xóa chuyến bay thành công!, redirect về QLChuyenBay','DB: CHUYENBAY, LOTRINH, HANGGHE_GIA của CBtest bị xóa'],
['TC_ADMIN_04','Xóa chuyến bay đã có vé bán','Kiểm tra ràng buộc: không xóa được khi đã có vé','1. Đăng nhập Admin\n2. Vào QLChuyenBay\n3. Click Xóa CB01 (đã có VEMAYBAYs)','MACB: CB01 (có 3 vé bán)','Hiển thị lỗi: Không thể xóa chuyến CB01 vì đã có vé được bán!','DB: CB01 vẫn tồn tại, không bị xóa'],
['TC_ADMIN_05','Cập nhật trạng thái chuyến bay tự động','Kiểm tra Cursor sp_UpdateFlightStatus','1. Đăng nhập Admin CV05 hoặc CV09\n2. Vào QLChuyenBay\n3. Click Cập nhật trạng thái chuyến bay','Gọi EXEC sp_UpdateFlightStatus_Cursor\nCB01: GIOCATCANH=GETDATE()+12h','Hiển thị: Đã cập nhật trạng thái cho N chuyến bay\nChuyến còn nhiều giờ: Chờ bay; Đang trong giờ bay: Đang bay; Quá giờ hạ cánh: Đã hạ cánh','DB: CHUYENBAY.TRANGTHAI được cập nhật đúng theo GETDATE()'],
['TC_ADMIN_06','Phân quyền: NV không phải Admin truy cập QLPerson','Kiểm tra [PhanQuyenAdmin] filter','1. Đăng nhập Admin với NV01 (CV01, không phải CV05/CV09)\n2. Truy cập /Admin/QLPerson','Session[AdminUser].MACV = CV01','Hệ thống trả về lỗi 403 hoặc redirect về trang không có quyền','Không vào được /Admin/QLPerson'],
['TC_ADMIN_07','Thêm nhân viên mới','Admin thêm nhân viên','1. Đăng nhập Admin CV05\n2. Vào /Admin/QLPerson\n3. Nhập MANV: NV11, TENNV, SDT, MACV: CV01, MATKHAU\n4. Click Thêm','MANV: NV11\nTENNV: Nguyễn Thị Mới\nSDT: 0912345611\nMACV: CV01\nMATKHAU: pass123','Nhân viên mới được thêm, hiển thị trong danh sách','DB: NHANVIEN có bản ghi NV11'],
['TC_ADMIN_08','Xóa nhân viên - Chuyển giao dữ liệu','Kiểm tra Proc sp_DeleteEmployee_SafeTransaction','1. Đăng nhập Admin NV05\n2. Vào QLPerson\n3. Click Xóa NV01','MANV bị xóa: NV01\nAdmin hiện tại: NV05','Hiển thị: Đã xóa nhân viên NV01 và chuyển giao dữ liệu thành công','DB: NV01 bị xóa khỏi NHANVIEN; VEMAYBAY và PHIEUDATVE của NV01 được chuyển sang MANV=NV05'],
['TC_ADMIN_09','Xóa Giám đốc cuối cùng - Trigger bảo vệ','Kiểm tra Trigger trg_SafeGuard_Director','1. Đăng nhập Admin CV09\n2. Vào QLPerson\n3. Thử xóa NV09 (Giám đốc CV09 duy nhất)','MANV: NV09 (chức vụ CV09 duy nhất)','Hệ thống báo lỗi: LỖI: Không thể xóa hoặc giáng chức Giám đốc cuối cùng!\nTransaction bị ROLLBACK','DB: NV09 vẫn tồn tại, trigger hoạt động đúng'],
['TC_ADMIN_10','Đổi chức vụ Giám đốc cuối cùng','Trigger bảo vệ việc đổi MACV của Giám đốc cuối','1. Đăng nhập Admin\n2. Vào SuaNhanVien của NV09\n3. Đổi MACV từ CV09 sang CV01\n4. Click Lưu','MANV: NV09\nMacv mới: CV01 (giáng chức)','Hệ thống báo lỗi từ Trigger: Không thể giáng chức Giám đốc cuối cùng\nKhông cho lưu','DB: NV09.MACV vẫn là CV09'],
['TC_ADMIN_11','Thống kê doanh thu theo tháng','Kiểm tra sp_TinhTongDoanhThu_Thang','1. Đăng nhập Admin\n2. Vào /Admin/ThongKeTheoThang\n3. Chọn tháng: 11, năm: 2025\n4. Click Tính','Tháng: 11, Năm: 2025','Hiển thị tổng doanh thu tháng 11/2025 = 26.500.000 (từ dữ liệu mẫu CHITIETVE)','Kết quả khớp với EXEC sp_TinhTongDoanhThu_Thang 11, 2025, @TongDT OUTPUT'],
['TC_ADMIN_12','Xuất báo cáo Excel','Kiểm tra export Excel từ Admin ThongKe','1. Đăng nhập Admin\n2. Vào /Admin/ThongKe\n3. Chọn khoảng thời gian\n4. Click Xuất Excel','startDate: 2025-11-01\nendDate: 2025-11-30','File .xlsx được tải xuống, có header đúng và dữ liệu doanh thu theo chuyến bay','File Excel có 5 cột: Mã CB, Ngày Bay, Số Vé, Doanh Thu, Giá TB'],
['TC_ADMIN_13','Sao lưu DB Full Backup','Kiểm tra chức năng Backup Full','1. Đăng nhập Admin CV09\n2. Vào /Admin/CaiDat\n3. Nhập tên: Backup_Test\n4. Chọn loại: Full\n5. Click Sao lưu','backupName: Backup_Test\nbackupType: full','Hiển thị: Sao lưu Toàn bộ (Full) thành công! File lưu tại D:\\Backups_QLMayBay\\QLMayBay_FULL_xxx.bak','File .bak được tạo tại D:\\Backups_QLMayBay\\, gọi thành công sp_BackupDatabase'],
['TC_ADMIN_14','Phục hồi DB từ file backup','Kiểm tra chức năng Restore','1. Đăng nhập Admin CV09\n2. Vào /Admin/CaiDat\n3. Chọn file .bak hợp lệ\n4. Click Phục hồi','File: QLMayBay_FULL_xxx.bak (hợp lệ)','Hiển thị: Phục hồi dữ liệu thành công! Hệ thống đã trở lại trạng thái cũ','DB: Được phục hồi thành công, dữ liệu quay về trạng thái tại thời điểm backup'],
['TC_ADMIN_15','Phục hồi DB - Không chọn file','Negative: Restore khi không upload file','1. Đăng nhập Admin CV09\n2. Vào /Admin/CaiDat\n3. Không chọn file\n4. Click Phục hồi','File: Không chọn (null)','Hiển thị: Vui lòng chọn file backup (.bak) để phục hồi','DB: Không có thay đổi nào'],
['TC_ADMIN_16','Tìm kiếm nhân viên theo MANV','Kiểm tra chức năng tìm kiếm','1. Đăng nhập Admin\n2. Vào QLPerson\n3. Nhập MANV: NV05\n4. Click Tìm','MANV: NV05','Hiển thị đúng thông tin của NV05: Hoàng Thị E, SĐT 0905678901, CV05','Danh sách chỉ hiển thị 1 kết quả là NV05'],
['TC_ADMIN_17','Thống kê KH theo quốc gia','Kiểm tra fn_ThongKeKhachTheoQuocGia','1. Đăng nhập Admin\n2. Vào /Admin/ThongKeQuocGia','Gọi SELECT * FROM fn_ThongKeKhachTheoQuocGia()','Hiển thị bảng thống kê: Việt Nam=8, Mỹ=1, Hàn Quốc=1 (theo dữ liệu mẫu)','Kết quả khớp với COUNT(*) GROUP BY QUOCGIA trong KHACHHANG'],
['TC_ADMIN_18','Admin quản lý vé - Đối soát check-in','Admin thay đổi trạng thái check-in trên QLVe','1. Đăng nhập Admin\n2. Vào /Admin/QLVe\n3. Chọn vé TKTxxxx\n4. Click Toggle Check-in','MaVe: TKTxxxx (chưa check-in)','Trạng thái chuyển sang: Đã check-in, THOIGIAN_CHECKIN = NOW()','DB: CHECKIN.TRANGTHAI=Đã check-in']
]
r4=r
for i,tc in enumerate(tcs4):
    row(r4,*tc,r-2+i)
    r4+=1
r=r4


tcs5=[
['TC_DB_01','Đối soát CHITIETVE sau thanh toán','Integration DB: Kiểm tra CHITIETVE được ghi đúng','1. Thực hiện đặt vé và thanh toán cho 2 HK trên CB01\n2. Truy vấn SQL: SELECT * FROM CHITIETVE WHERE MAPHIEU=(SELECT MAPHIEU FROM PHIEUDATVE WHERE MAGH=MAGH_vua_tao)','2 HK, CB01, hạng Phổ thông, giá 1.950.000/vé','CHITIETVE có 2 bản ghi: MAVE1 và MAVE2, GIATIEN=1.950.000 mỗi vé, NGAYDAT=GETDATE()','DB: 2 dòng trong CHITIETVE, FK hợp lệ với VEMAYBAY và PHIEUDATVE'],
['TC_DB_02','Trigger THONGKE_DOANHTHU khi thêm CHITIETVE','Kiểm tra Trigger trg_CapNhatDoanhThu','1. Thêm 1 bản ghi vào CHITIETVE (ghế mới CB02, giá 1.500.000)\n2. Kiểm tra bảng THONGKE_DOANHTHU','INSERT CHITIETVE (MAVE_moi, PDVxxx, GETDATE(), 1500000)','THONGKE_DOANHTHU.CB02.SOLUONGVE tăng 1\nTONGDOANHTHU tăng 1.500.000','DB: THONGKE_DOANHTHU được tự động cập nhật bởi Trigger'],
['TC_DB_03','Kiểm tra ràng buộc CHECK trạng thái chuyến bay','DB: Chỉ nhận giá trị trong danh sách cho phép','1. Thử INSERT trực tiếp vào CHUYENBAY với TRANGTHAI bất hợp lệ\n2. EXEC SQL: INSERT INTO CHUYENBAY VALUES (CBtest, N\'Sai trạng thái\', MB01)','TRANGTHAI: Sai trạng thái (không thuộc: Đang bay, Chờ bay, Đã hạ cánh, Hủy)','SQL Server trả về lỗi: CHECK constraint failed (CHK_CB_TRANGTHAI)','DB: Không có bản ghi mới trong CHUYENBAY'],
['TC_DB_04','Kiểm tra ràng buộc FK GioHang_HanhKhach','DB: MAGH phải tồn tại trong GIOHANG','1. Thử INSERT GIOHANG_HANHKHACH với MAGH không tồn tại\n2. EXEC SQL: INSERT INTO GIOHANG_HANHKHACH...','MAGH: GHkhoonton (không tồn tại trong GIOHANG)','SQL trả về lỗi: FOREIGN KEY constraint failed','DB: Không có bản ghi mới'],
['TC_DB_05','CURSOR thống kê doanh thu chạy đúng','Kiểm tra Cursor inline thống kê từng chuyến','1. Chạy đoạn Cursor thống kê doanh thu\n2. So sánh kết quả với SQL tay: SELECT SUM(CT.GIATIEN) FROM CHITIETVE CT JOIN VEMAYBAY V ON CT.MAVE=V.MAVE WHERE V.MACB=CB01','Cursor duyệt qua 10 chuyến bay (CB01-CB10)','Mỗi chuyến bay in đúng tổng doanh thu, khớp với CHITIETVE.GIATIEN SUM theo MACB','Kết quả CB01: 4tr+4.8tr+5tr = khớp; CB10: 0 (chưa có vé)'],
['TC_DB_06','sp_DonVeHetHan - Dọn giỏ hàng hết hạn','Kiểm tra Proc dọn dẹp giỏ hàng','1. Tạo giỏ hàng GHtest với THOIGIANGIU = GETDATE()-1h (đã hết hạn)\n2. Gọi EXEC sp_DonVeHetHan','GIOHANG_CHITIET.THOIGIANGIU < GETDATE()','GIOHANG_CHITIET bị xóa; GIOHANG.TRANGTHAI=Đã hết hạn','DB: Bản ghi GHtest trong GIOHANG_CHITIET bị xóa; GIOHANG.TRANGTHAI cập nhật'],
['TC_HOSO_01','Cập nhật hồ sơ KH','Kiểm tra cập nhật thông tin cá nhân','1. Đăng nhập KH01\n2. Vào HoSo\n3. Đổi tên: Nguyễn Minh Khoa 2\n4. Đổi địa chỉ: Hà Nội Mới\n5. Click Lưu','TENKH: Nguyễn Minh Khoa 2\nDIACHI: Hà Nội Mới\nGTINH: Nam','Hồ sơ được lưu, Session[UserName] cập nhật, redirect về HoSo','DB: KHACHHANG.TENKH=Nguyễn Minh Khoa 2, DIACHI=Hà Nội Mới'],
['TC_HOSO_02','Upload ảnh đại diện','Kiểm tra chức năng upload ảnh','1. Đăng nhập KH01\n2. Vào HoSo\n3. Chọn file ảnh .jpg\n4. Click Lưu','File: avatar.jpg (hợp lệ, < 5MB)','Ảnh được lưu vào ~/Content/Images/User/KH01.jpg, Session[Image] cập nhật','File tồn tại tại đường dẫn server, tên file = MAKH.ext'],
['TC_HUSO_03','Cập nhật ngày sinh sai định dạng','Negative: Ngày sinh không hợp lệ','1. Đăng nhập KH01\n2. Vào HoSo\n3. Nhập NgaySinh: 32/13/2000 (sai)\n4. Click Lưu','NgaySinh: 32/13/2000','Hệ thống báo lỗi parse ngày (DateTime.Parse lỗi) hoặc validation error','DB: NGSINH không thay đổi'],
['TC_HUYE_01','Hủy vé chưa thanh toán','Kiểm tra hủy đơn hàng chưa thanh toán','1. Đăng nhập KH01\n2. Vào VeCuaToi\n3. Tìm đơn hàng Đang chọn\n4. Click Hủy','MAGH=GHxxx, TRANGTHAI=Đang Chon','Hiển thị: Hủy đơn hàng thành công!, ghế được giải phóng','DB: GIOHANG_HANHKHACH bị xóa; GIOHANG_CHITIET bị xóa'],
['TC_HUYE_02','Hủy vé đã thanh toán','Negative: Không cho hủy vé đã thanh toán','1. Đăng nhập KH01\n2. Vào VeCuaToi\n3. Tìm đơn Đã thanh toán\n4. Thử click Hủy','MAGH=GH01, TRANGTHAI=Đã Thanh Toán','Hiển thị lỗi: Không thể hủy vé đã thanh toán!','DB: Không có thay đổi, vé vẫn tồn tại'],
['TC_SORT_01','Sort theo giờ bay sớm nhất','Kiểm tra sort chuyến bay theo giờ khởi hành','1. Tìm kiếm chuyến bay\n2. Click Sort: Bay sớm nhất','Sort: early (theo GioCatCanh ASC)','Chuyến bay hiển thị theo thứ tự GioCatCanh tăng dần','Chuyến bay có GioCatCanh sớm nhất hiển thị đầu tiên'],
['TC_SORT_02','Sort theo thời gian bay ngắn nhất','Kiểm tra sort theo thời lượng bay','1. Tìm kiếm chuyến bay\n2. Click Sort: Bay nhanh nhất (TimeSpan)','Sort: timespan','Chuyến bay hiển thị theo thứ tự (GioHaCanh - GioCatCanh) tăng dần','Chuyến bay có thời gian bay ngắn nhất hiển thị đầu']
]
r5=r
for i,tc in enumerate(tcs5):
    row(r5,*tc,r-2+i)
    r5+=1
r=r5
tcs6=[
['TC_SEC_01','Truy cập Admin không có quyền','EP: Người dùng không hợp lệ hoặc Khách hàng cố tình truy cập URL Admin','1. Đăng nhập với tài khoản Khách hàng (KH01) hoặc chưa đăng nhập\n2. Nhập trực tiếp URL /Admin/QLChuyenBay lên trình duyệt','URL = /Admin/QLChuyenBay, Session = Khách hàng hoặc rỗng','Hệ thống chặn truy cập, redirect về trang Đăng nhập hoặc hiển thị lỗi 403 (Không có quyền)','Session không thay đổi, DB không bị tác động'],
['TC_SEC_02','Nhân viên không đủ quyền Backup/Restore','EP: Nhóm quyền không thuộc CV05/CV09 cố gắng thực hiện đặc quyền','1. Đăng nhập với NV01 (CV01 - Nhân viên bán vé)\n2. Cố tình truy cập /Admin/CaiDat hoặc gửi POST request để backup','Account = NV01 (CV01)','UI ẩn menu Cài đặt. Nếu cố tình truy cập, trả về lỗi Access Denied, không thực thi SP sp_BackupDatabase','File backup không được tạo, DB giữ nguyên'],
['TC_BVA_01','Đặt vé với đúng 9 hành khách','BVA: Số lượng hành khách ở giới hạn trên','1. Tìm chuyến bay\n2. Nhập Số lượng hành khách: 9\n3. Click Tìm chuyến','Số lượng HK = 9','Hệ thống cho phép tìm kiếm và đặt 9 ghế, form sinh ra đúng 9 dòng thông tin','Session[passenger] = 9'],
['TC_BVA_02','Đặt vé với 10 hành khách','BVA: Số lượng hành khách vượt giới hạn trên','1. Tìm chuyến bay\n2. Cung cấp Số lượng hành khách: 10 (qua UI hoặc intercept request)\n3. Click Tìm chuyến','Số lượng HK = 10','Hệ thống báo lỗi "Số lượng hành khách tối đa là 9", ngăn chặn tiếp tục','Không lưu vào Session hay DB'],
['TC_BVA_03','Check-in đúng 24h trước giờ bay','BVA: Thời gian mở check-in','1. Có vé hợp lệ\n2. Đợi đến đúng thời điểm (Giờ cất cánh - 24h0m0s)\n3. Click Check-in','Thời gian hiện tại = Giờ cất cánh - 24 tiếng','Hệ thống cho phép check-in, nút check-in được kích hoạt','CHECKIN.TRANGTHAI = Đã check-in'],
['TC_BVA_04','Check-in đúng 60 phút trước giờ bay','BVA: Thời gian đóng check-in','1. Có vé hợp lệ\n2. Đợi đến đúng thời điểm (Giờ cất cánh - 60m0s)\n3. Click Check-in','Thời gian hiện tại = Giờ cất cánh - 60 phút','Cho phép check-in thành công ở giây phút cuối cùng trước khi đóng cổng','CHECKIN.TRANGTHAI = Đã check-in'],
['TC_BVA_05','Thanh toán ở giây thứ 0 của bộ đếm ngược','Real-time/BVA: Xử lý timer giữ chỗ 10 phút','1. Giữ chỗ (countdown 10 phút)\n2. Ở trang thanh toán VNPay, chờ đến đúng giây 0 của phút cuối\n3. Bấm xác nhận thanh toán','Giao dịch callback về đúng lúc Timer = 0 hoặc THOIGIANGIU = GETDATE()','Hệ thống tiếp nhận thanh toán, nếu đã xóa ghế thì báo lỗi và lưu log hoàn tiền, nếu chưa xóa thì sinh vé thành công','Tránh trường hợp bị treo giao dịch hoặc mất tiền không có vé'],
['TC_NEG_01','Upload avatar sai định dạng hoặc quá dung lượng','Negative: Kiểm tra validation file upload','1. Đăng nhập KH01\n2. Vào Hồ sơ, upload file malware.exe hoặc ảnh > 5MB\n3. Bấm Lưu','File = script.exe, hoặc image.jpg (10MB)','JS chặn ở client hoặc Controller báo lỗi "Định dạng file không hợp lệ" / "Dung lượng vượt mức cho phép"','File không được lưu lên server, DB giữ nguyên'],
['TC_NEG_02','Lỗi kết nối SQL khi đang lưu vé','Negative/Atomicity: Đảm bảo toàn vẹn dữ liệu (Transaction)','1. Thanh toán VNPay thành công\n2. Hệ thống gọi sp_DatVe, giả lập ngắt kết nối DB hoặc throw Exception giữa chừng','VNPay success, DB insert lỗi','Giao dịch phải được ROLLBACK hoàn toàn. Không có vé rác được sinh ra, tiền bị treo được cảnh báo để hoàn trả','VEMAYBAY, CHITIETVE không có dữ liệu lỗi'],
['TC_NEG_03','Phục hồi DB bằng file hỏng hoặc sai version','Negative: Kiểm tra exception của Restore DB','1. Đăng nhập CV09, vào Cài đặt -> Phục hồi\n2. Chọn file corrupted.bak (file text đổi đuôi) hoặc của bản SQL cao hơn\n3. Bấm Phục hồi','File = corrupted.bak','Try-catch bắt lỗi RESTORE DATABASE failed, hiển thị thông báo "File backup không hợp lệ hoặc bị lỗi"','DB hiện tại vẫn hoạt động bình thường không bị ảnh hưởng'],
['TC_DT_01','Quyết định lọc chuyến bay phức tạp','Decision Table: Kết hợp Hãng + Giá + Giờ bay','1. Tìm chuyến bay 1 chiều\n2. Chọn Hãng: Airbus, Giá: < 2 triệu, Giờ: Sáng (6h-12h)\n3. Bấm Lọc','Điều kiện = (Airbus) AND (Giá < 2M) AND (Sáng)','Chỉ hiển thị các chuyến bay thỏa mãn đồng thời 3 điều kiện. Nếu không có thì báo "Không tìm thấy"','ListChuyenBay chỉ chứa kết quả đúng logic'],
['TC_ST_01','Kiểm thử chuyển trạng thái Vòng đời Vé','State Transition: Ghế Trống -> Đang Chọn -> Đã Thanh Toán -> Đã Check-in -> Hủy','1. Chọn ghế -> Thanh toán -> Check-in\n2. Kiểm tra DB tại mỗi bước','Trạng thái tương ứng của GIOHANG, VEMAYBAY, CHECKIN','Trạng thái chuyển đúng logic. Không thể check-in khi chưa thanh toán, không thể hủy khi đã check-in','Trạng thái dưới DB khớp với thực tế vòng đời của vé']
]
r6=r
for i,tc in enumerate(tcs6):
    row(r6,*tc,r-2+i)
    r6+=1
r=r6

wb.save('BoCauHoi_TestCase_QuanLyMayBay.xlsx')
print('DONE! File: BoCauHoi_TestCase_QuanLyMayBay.xlsx, Total rows:', r-2)
